### ISSUE TITLE
Compute reachable set of discrete-time nonlinear system

### ISSUE THREAD

**Issue by jinsunl** [TUMcps/CORA#12]
Hello, 

The manual says params.R0 can be any set representation in section 'Basic Set Representations', but I'm having trouble on computing the reachable sets of discrete-time nonlinear system with initial set as constrained zonotope or zonotope bundle. Could you please provide a simple example script on how this can be done with CORA? Thanks!

**Comment by wetzlingerm** [comment]
Thank you for raising this issue. We have added the required functionality in the [last commit](https://github.com/TUMcps/CORA/commit/fdac35f592f56db101e8a4912e956e2e96be7287), so that conZonotope and zonoBundle objects can be used for the computation of reachable sets of nonlinearSysDT objects. We have enhanced the example of this system class (example_nonlinearDT_reach_cstrDisc) by params.R0 of classes conZonotope and zonoBundle for you to see how it works. Please note that the plotting of conZonotope objects can be quite time-consuming, so that the plotting method needs to be chosen carefully.

Let us know if you encounter any more troubles.
