### ISSUE TITLE
Different results in Pontryagin difference with CORA 2018 and 2020

### ISSUE THREAD

**Issue by ddlmcp** [TUMcps/CORA#16]
[ZE.zip](https://github.com/TUMcps/CORA/files/5783103/ZE.zip)

When performing the operation Z-E with the zonotopes Z and E (see attachment), CORA returns an empty set in version 2020 and the correct/expected set in version 2018.

**Comment by TUMcps** [comment]
For me it also worked with CORA 2020 (see screenshot) using Matlab R2017b and MPT toolbox version 3.1.8. It could be that it is a version problem either of Matlab or the MPT toolbox. Could you please tell us which version you use, then we will try to reproduce the issue.

![ScreenshotMinkwoskiDiffernce](https://user-images.githubusercontent.com/40696173/104197696-a1341400-5425-11eb-854c-7e1fa82f6ce7.png)

It is also important that Z-E is the Minkowski difference, while Z + (-E) is the Minkowski addition with the negated zonotope, which are two different things.

**Comment by ddlmcp** [comment]
Hi, thank you.
    I'm using MPT 3.2.1 in Matlab 2020b Update 3. I can't test it in another configuration right now. If I can manage to change it and test I'll post it here.

Thanks

**Comment by TUMcps** [comment]
Thank you! Now I was able to reproduce the issue. The problem was caused since the MPT toolbox, which CORA uses for polytope computations, returned different results on different Matlab versions. I therefore fixed the issue in commit 0d3bec9 by using the CORA function for checking if a polytope is empty instead of using the MPT function.

**Comment by ddlmcp** [comment]
Great! Thank you.
