### ISSUE TITLE
Issue in Zonotope volume approximation

### ISSUE THREAD

**Issue by ckurtz22** [TUMcps/CORA#17]
https://github.com/TUMcps/CORA/blob/f4e674929bb2bb0c4859a1afa3838220cf60f0cf/contSet/%40zonotope/volume.m#L83

index slice is [end-n-r+1, end], but r is binary here. Is r supposed to be the rank of the generators?

**Comment by wetzlingerm** [comment]
The description and code have been improved in the [last commit](https://github.com/TUMcps/CORA/commit/5c1e767a8bffc8e9717f90093cb6f98c29768885). The input argument r represents the number of filtered generators (in addition to the full rank requirement so that the volume is non-zero) which are used to compute the volume of the zonotope.

**Comment by ckurtz22** [comment]
Oooh thank you. The description was just incorrect in the Cora 2020 release.
