### ISSUE TITLE
parametricDynamicFIile not present

### ISSUE THREAD

**Issue by ChitraDangwal** [TUMcps/CORA#28]
While trying to run my model, which is related to the non-linear uncertain parameter , using the example from nonlinParamSys. I run into an error which shows - "@parametricDynamicFIile*" not present. For the examples present these "parametricDynamicFile" are present in the auxiliary folder while for my test models these file are not created.

**Comment by wetzlingerm** [comment]
Hi,
The auxiliary folder for your system is generated, when the function `derivatives` is called within `reach`. All files necessary for the current setting as defined by `params` and `options` are generated, which includes the parametricDynamicFile.

Please provide me with your setting of `params.paramInt`, `options.alg`, and `options.tensorOrder` and also include the stack of the error message that you obtained so that I can replicate your error. Thanks in advance!
