### ISSUE TITLE
Check for incorrect argument data type or missing argument in call to function 'config_linearSys_reach'.

### ISSUE THREAD

**Issue by jinaynitinpatel** [TUMcps/CORA#33]
Getting an error while calling functions from configfiles.
Error: _Check for incorrect argument data type or missing argument in call to function 'config_linearSys_reach'._
I am calling config_linearSys_reach(sys, params, options) and getting the above error. 
Here, sys is 'linearSys' object, params is 'struct' and options is also 'struct'.

**Comment by wetzlingerm** [comment]
I suppose you are not calling config_linearSys_reach yourself, but via the validateOptions function call. Since your input arguments are correct, the function should at least be entered.

One explanation could be that config_linearSys_reach takes a linearSys object as the first input argument, but is not located inside the @linearSys folder. But this does not seem to be an issue in my case (as well as for anybody else so far calling config_linearSys_reach). Is the error reproducible on your side? In that case, I would be interested in seeing the full call stack, maybe I can set up a similar example to figure out what is going on.

Personally, I have encountered the given error message in other contexts, where restarting MATLAB and running the same code fixed the issue (impeding reproducibility). I admit that such a solution is unsatisfactory.
