### ISSUE TITLE
Linearization error available ?

### ISSUE THREAD

**Issue by gpensta** [TUMcps/CORA#47]
In the "linearize.m" file, you wrote in a comment: "% linearize - linearizes the nonlinear system; linearization error is not included yet". 
But at the end of the file, you reference the linearization error using " [dA,dB] = lin_error2dAB(options.Ronestep,options.U,obj.hessian,p)"
I am a bit lost, is it possible to access all the linearization errors for a Ronestep?
Thank you in advance.

**Comment by wetzlingerm** [comment]
The comments in the file `@nonlinearSys/linearize.m` are indeed a bit contradictory. The main purpose of the file is to compute linearized dynamics, to which one has to add a linearization error in order to obtain a differential inclusion of the original nonlinear dynamics. This is the case for the algorithms accessible via `options.alg='lin'` and `options.alg='poly'`. For these algorithms, the linearization error is computed in the loop in lines `107-146` in the file `@contDynamics/reach`, and the reachable set due to the linearization error is computed in lines `153-162`.

However, the algorithm with `options.alg='linRem'` works differently: Instead of separating linearized dynamics and linearization error into two separate terms, the linearization error is included in the linearized dynamics, resulting in a set of system matrices. You can see this in lines `72-73` in `@nonlinearSys/linearize.m`, where the system matrix `A` and the input matrix `B` are instantiated as `matZonotope` objects, i.e., matrix zonotopes. However, these require some prior information, namely the variable `options.Ronestep`, which is computed in the auxiliary function `aux_initReach_linRem` in the file `@nonlinearSys/initReach.m`. The reachable set is then essentially computed in the call to `initReach` in line `65` in `@contDynamics/linReach.m`. Crucially, there is no separate linearization error term since the linearized dynamics represented by the matrix zonotopes for linearization error is already accounted for in the matrix zonotopes representing the linearized dynamics.

If you have more questions, please let us know!

**Comment by gpensta** [comment]
Thank you very much for this very clear answer!
