### ISSUE TITLE
Array indices must be positive integers or logical values, 

### ISSUE THREAD

**Issue by akaph2p** [TUMcps/CORA#54]
Hi,

Im using CORA v2024.2.1 on a nonlinear system. I receive this error:

```
Array indices must be positive integers or logical values.

Error in nonlinearSys/linReach_adaptive (line 303)
            if varphi < options.zetaphi(options.minorder+1)

Error in nonlinearSys/reach_adaptive (line 83)
        [Rnext.ti,Rnext.tp,options] = linReach_adaptive(obj,options,options.R);

Error in contDynamics/reach (line 68)
        [timeInt,timePoint,res,~,options] = reach_adaptive(obj,params,options);

Error in verification_reach_turbine (line 36)
R = reach(turbine, params, options);
```

I have tried other nonlinear systems and they are working fine, but this .m file seems to have issues.

**Comment by akaph2p** [comment]
```
function dx = odes_reach_turbine(x,u)

% Parameters
r = 25/24; % pressure ratio across the turbine = inlet pressure /outlet pressure
eta = 1; % Turbine isentropic efficiency
Cturb = 0.55;

% Control
Ts = x(1);
mdots = x(2);

Tsin =(Ts)*(1-eta*(1-(1/r))); % 600 at ss

% differential equations
% turbine
dx(1,1) = mdots*Cturb*(Ts - Tsin);
dx(2,1) = 0;
end
```

**Comment by akaph2p** [comment]
```
% Parameters
r = 1.1; % pressure ratio across the turbine = inlet pressure /outlet pressure
eta = 1; % Turbine isentropic efficiency
Cturb = 0.55;


%% Highpower ss, mdots compromised

% Parameters --------------------------------------------------------------
params.tFinal = 200;

Ts0 = 625;
mdots0 = 340;

params.R0 = zonotope([  [Ts0; mdots0], diag([0,0])   ]);
params.U = zonotope([0,0]);


% Reachability Settings ---------------------------------------------------

options.alg = 'lin-adaptive';
options.maxError = [0.01;0.01];

% System Dynamics ---------------------------------------------------------

turbine = nonlinearSys(@odes_reach_turbine,2,0);

% Reachability Analysis ---------------------------------------------------

tic
R = reach(turbine, params, options);
tComp = toc;
disp(['computation time of reachable set: ',num2str(tComp/60) ' mins']);


% Simulation --------------------------------------------------------------
tic
simOpt.points = 5;
simRes = simulateRandom(turbine, params, simOpt);
tComp = toc;
disp(['computation time of simulation: ',num2str(tComp/60) ' mins']);
```

**Comment by wetzlingerm** [comment]
Thank you for raising this issue!

Rewriting the given dynamics, one obtains
`x1' = x1 * x2 * C_turb*eta*(1-1/r)`
`x2' = 0`
The behavior of this system depends on the values for the factors `x2` and `C_turb*eta*(1-1/r)`. If the product of these factors is positive, the state `x1` will blow up to +Inf. In contrast, if the product is negative, `x1` will converge to 0. In fact, the specific configuration of initial state and parameter values yields the 1D linear differential equation
`x' = 7.48x, x(0) = 625`,
for which the analytical solution is
`x(t) = 625*exp(7.48*t)`,
which obviously blows up to +Inf over time.

The adaptive algorithm for nonlinear systems cannot deal with the given system since the dynamics are linear and the initial uncertainty is zero, which breaks the algorithm, as it is too much of a special case. We will look into this issue in the future. In the meantime

- reformulate the system as a linear system and use an algorithm for linear systems, or
- use an initial set for `params.R0` instead of a single point.

In both cases, the behavior will still depend on the sign of the factors in the equation for `x1'` as discussed above. If the state goes to Inf, you might encounter further error messages.

Let us know if you have further questions!

**Comment by akaph2p** [comment]
So, i tried to add an initial set for ```param.R0```, but now im getting a different error.

```
Error using inputArgsCheck (line 111)
Wrong value for the first input argument.
  The right value: numeric (nonnan)
  Type 'help zonotope' for more information.

Error in zonotope>aux_checkInputArgs (line 171)
            inputArgsCheck({ ...

Error in zonotope (line 74)
        aux_checkInputArgs(c,G,nargin);

Error in abstractionError_adaptive (line 106)
    VerrorDyn = zonotope(0*err,diag(err));

Error in nonlinearSys/linReach_adaptive (line 193)
                    abstractionError_adaptive(obj,options,Rmax,Rtemp);

Error in nonlinearSys/reach_adaptive (line 83)
        [Rnext.ti,Rnext.tp,options] = linReach_adaptive(obj,options,options.R);

Error in contDynamics/reach (line 68)
        [timeInt,timePoint,res,~,options] = reach_adaptive(obj,params,options);

Error in verification_reach_turbine (line 36)
R = reach(turbine, params, options);
```

The only thing ive changed from my earlier code is 
``` params.R0 = zonotope([  [Ts0; mdots0], diag([10,10])   ]); ```

**Comment by wetzlingerm** [comment]
This error relates to my earlier statement `If the state goes to Inf, you might encounter further error messages.`. At this point, the values become so large that MATLAB converts them to Inf, which leads to NaN in a subsequent computation, which causes this error.

**Comment by akaph2p** [comment]
I see. Thank you for your explanation.
