### ISSUE TITLE
Question about 'dim' 

### ISSUE THREAD

**Issue by DwZhang01** [TUMcps/CORA#57]
I run the example 'bouncing ball' with CORA v2024 but encount the following question that the use of 'dim' is incorrect. 
>>>    
hybridAutomaton>aux_checkInputArgs (Line 117)  
           if dim(locs(i).invariant) ~= locs(i).contDynamics.dim
![image](https://github.com/user-attachments/assets/adc8fa4b-678f-49bd-a129-1e9eed4f0e00)

**Comment by wetzlingerm** [comment]
Hello,
There is no file in CORA with the exact name `BouncingBall` (as seen in your screenshot). Instead, I have executed the bouncing ball example in `example_hybrid_reach_01_bouncingBall` on CORA v2024.0.0 and v2024.4.1 (latest version) -- both are ok. 

Which specific version are you using?

From the error message you described, I would assume that either the object stored in `locs(i).contDynamics` or the object stored in `locs(i).invariant` is not correct, e.g., due to typo in the definition of `locs`.

Can you send us your `BouncingBall` file?

**Comment by DwZhang01** [comment]
Thanks for your help sincerely! 

I'm using CORA v2024.4.1 (latest version) and the `BouncingBall` is exactly the same as the code example on [the official website](https://tumcps.github.io/CORA/pages/hybrid-systems/index.html) .

The 'example_hybrid_reach_01_bouncingBall' also returns error as below :
![image](https://github.com/user-attachments/assets/31220f56-90a0-4822-a77b-0dcce6690844)

I also installed AROC (2022) and 'runUnitTests' returns 1 Passed,17 Failed. I'm not sure if there's something incompatible with CORA (v2024.4.1) and AROC (2022). I installed CORA before AROC.  Maybe the problem can be replicated.

**Comment by DwZhang01** [comment]
The error may be accidental. I will reinstall CORA and try again.

**Comment by DwZhang01** [comment]
I reinstalled CORA and the problem is fixed. 

The error may comes from the incompatibility of the './CORA-master/global/thirdparty/fourier' and the './mpt3/tbxmanager/toolboxes/fourier'. I delete the former folder path in MATLAB and only use the latter one , and the problem is solved. Maybe this provides some insight of the problem existing in the code structure. 

CORA really helps me a lot!  

Thanks again for your help!

**Comment by wetzlingerm** [comment]
Indeed, CORA v2024 is incompatible with AROC 2022 due to replacing the polytope functionality from the mpt toolbox by a CORA-built-in @polytope class. Therefore, please remove `tbxmanager/toolboxes/mpt` from your path when using CORA v2024. As you mentioned, we have integrated `tbxmanager/toolboxes/fourier` into our `global` folder, so the duplicate indeed causes problems.

I was informed that there could be a new release of AROC at the end of this year, compatible with CORA v2025 (which will be released in a couple of weeks).

We are very happy that you enjoy using CORA! If you have any further questions, let us know.
