### ISSUE TITLE
linearization causes error "Left limit larger than right limit"

### ISSUE THREAD

**Issue by MaxGaukler** [TUMcps/CORA#7]
The following nonlinear reachability computation creates an empty interval (which then triggers bug #6 ):

[Nonlinear_tank.zip](https://github.com/TUMcps/CORA/files/3635843/Nonlinear_tank.zip)

```
>> Nonlinear_tank
Left limit larger than right limit
Error using  + 
Matrix dimensions must agree.

Error in  +  (line 56)
    res.inf = res.inf + summand.inf;

Error in tie (line 63)
obj.taylor.F=Asum+obj.taylor.error;

Error in linearSys/initReach (line 41)
obj = tie(obj,options);

Error in linReach (line 58)
R = initReach(linSys,Rdelta,linOptions);

Error in nonlinearSys/initReach (line 58)
    [Rti,Rtp,nr,perfInd] = linReach(obj,options,Rinit{iIteration},recur);

Error in nonlinearSys/post (line 36)
[Rnext,options] = initReach(obj,R.tp,options);

Error in contDynamics/reach (line 127)
    [Rnext,options]=post(obj,Rnext,options);

Error in Nonlinear_tank (line 47)
Rcont = reach(tank, options);
 ```

**Comment by wetzlingerm** [comment]
The given error is caused by the model defintion as explained subsequently.

The provided system models two water tanks, the first one of which is supplied by an inflow. The states are the water levels in the tanks and the uncertain input is the disturbance of the inflow. If this disturbance (that is, the input set) is too large, the analysis also considers cases in which water tank 1 is drained to a level below 0 which in consequence is responsible for the given error as the square root in the differential equation of state 1 is not defined for negative water levels.

In order to avoid this, either the disturbance has to be low or the system has to be modeled differently, e.g. by considering the case of an empty tank which can be done by hybrid systems.

**Comment by MaxGaukler** [comment]
Thanks for your diagnosis. You are right that the root cause is the problematic model definition. 

The current error message is somewhat misleading because it suggests that something is wrong within CORA. It would be better to catch the "empty interval" error and print something like "piecewise linearization failed near x=..., please check that your model is well-behaved (differentiable, finite)".

**Comment by wetzlingerm** [comment]
We acknowledge that the feedback given by the algorithms, including the occurence of errors, is not yet as elaborate as it should be, as demonstrated by this case. Improvements in this regard will be provided in the next release version.
