### ISSUE TITLE
zonotope 'and' operator

### ISSUE THREAD

**Issue by hitchaj** [TUMcps/CORA#9]
% Cora release 2020 installed. Matlab 2019b. Windows 10.
% the  following section works. although zono1&zono2 = empty
zono1=zonotope(0,[1,2]);
zono2=zonotope(5,1);
zono1&zono2

zono1=zonotope(-0.7965,[0.1067   -0.2881    0.1512    0.0534   -0.2368   -0.1073    0.0449   -0.1008   -0.1057 0.0270    0.0227   -0.0342    0.0024    0.0442   -0.0091   -0.0030    0.0246    0.0039    0.0479 -0.1852    0.5000         0]);
zono2=zonotope(2.3811,-0.1000);
% empty intersection
% next command will raise error: Error using interval. Lower limit larger than upper limit.
zono1 & zono2

**Comment by wetzlingerm** [comment]
Thank you for catching this error.

The [last commit](https://github.com/TUMcps/CORA/commit/dbbfef6fa7662217c333b40768f2787149f11f12) should resolve the given case, so that you obtain empty zonotopes in both cases. Note that one-dimensional zonotopes are exactly convertible to intervals which may simplify some of the operations.

**Comment by hitchaj** [comment]
> Thank you for catching this error.
> 
> The [last commit](https://github.com/TUMcps/CORA/commit/dbbfef6fa7662217c333b40768f2787149f11f12) should resolve the given case, so that you obtain empty zonotopes in both cases. Note that one-dimensional zonotopes are exactly convertible to intervals which may simplify some of the operations.

Thank you. It works now. I'm just trying to make my functions more compatible with different dimension. Quick check suffices for now.
